[workspace]
git_tag_name = "v{{ version }}"
git_release_type = "auto"
git_only = true
pr_labels = ["release"]
publish_timeout = "0s"

[[package]]
name = "pr-bro"
publish = false

[changelog]
protect_breaking_commits = true
